### ISSUE TITLE
Full Javascript render?

### ISSUE THREAD

**Issue by jdprojectcentral** [sukhcha-in/dart_web_scraper#13]
Hello does this get the data from a full website render including css and hidden dom etc? Does it provide headless browser? Trying to determine overall if it is a simple http request of data or a full render of a site like you would in a headless browser selenium, playwright etc?

**Comment by sukhcha-in** [comment]
@jdprojectcentral This uses simple `http` requests to fetch the html. You can use headless browser (https://pub.dev/packages/puppeteer) to scrape the website and pass the scraped html to `dart_web_scraper` for parsing using `WebParser.parse` method.

**Comment by jdprojectcentral** [comment]
Does this look to be maintained in the long term? Do you take commits from other users for improvement or added functionality?

**Comment by sukhcha-in** [comment]
> Does this look to be maintained in the long term?

Yes this will be maintained, we're using this package in our production apps. 

> Do you take commits from other users for improvement or added functionality?

Yes PRs are most welcome.
