### ISSUE TITLE
Dependency Inversion

### ISSUE THREAD

**Issue by arrrrny** [sukhcha-in/dart_web_scraper#15]
Dude, I havent tested your package yet, (sure I will) if this can delegate the web scraping to any html resolver. like dio,zikzak_inappwebview it would be fantastik!

Some websites have anti-scraping,and loosing coupling it to html package and just allowing the html input as an interface is the best way. I hope it can be easily done. I will share my thoughts after I use.

Thanks for contrubition!

**Comment by sukhcha-in** [comment]
Hi, You can pass pre-fetched html to `WebParser` as `Data` model. Data model contains pre-fetched html and a URL.

**Comment by arrrrny** [comment]
@sukhcha-in awesome! I will definitely take a look and use upcoming week.

**Comment by arrrrny** [comment]
@sukhcha-in I just started using it today. I love it. I had my internal extractor similar to this, yours is very clean.
I had a bit hard time figuring out actual json extractor since there was no example. But hey, we are programmers. No need to give everything in silver plate right?
